services:
  nodejs:
    build: .
    volumes:
      - /data/coolify/applications/zk4csk00g8os44w4cokw40so/rclone.conf:/root/.config/rclone/rclone.conf                                   
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - /data/coolify/applications/zk4csk00g8os44w4cokw40so/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "90:80"
    depends_on:
      - nodejs
    restart: always
